### ISSUE TITLE
Error with run dev and Screenshot the UI (please)

### ISSUE THREAD

**Issue by mgnica** [technix/atrament-ui#2]
Hi,

I got this error when running `npm run dev` and I think it may be a bad link in your code:
`Module not found: Error: Can't resolve 'preact/devtools' in '/Users/monica/atrament-ui/node_modules/preact-cli/lib/lib'
 @ ./node_modules/preact-cli/lib/lib/entry.js 6:1-27
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
`
Also, if possible could you screenshot your UI and add that to the documentation? I was hoping to run the code to get a look see of the UI to either use or make my own. I'm hoping for a draggable palette for the original atrament library.

Thanks.

**Comment by technix** [comment]
Hi!
Yep, it looks like dependencies are broken. Updated package.json, please check out the latest version.
Also please note: the UI itself is very sketchy and can be use only as a blueprint to build something based on it.

**Comment by mgnica** [comment]
Thanks, it works now! Could you screenshot the actual drawing pad UI part?
I'm being taken through a game in Russian(??).

**Comment by technix** [comment]
Sorry, what do you mean by "drawing pad"? 
The "atrament-ui" is a text game engine based on Ink.
